"""Stand-in for fakereasoning-api, to exercise main.js without a GPU.

Serves the three plausible response shapes plus the failure paths, with the
verbatim 2026-08-17 text from docs/model-contract.md.
"""
import json
import time
from http.server import BaseHTTPRequestHandler, HTTPServer

OFFICIAL = {
    "prediction": "fake",
    "reasoning": ("From low-level perspective: The lighting on the building and the shadows on "
                  "the objects do not match the overall light source direction.The textures on "
                  "the building and the surrounding objects appear inconsistent and lack "
                  "realistic detail. From high-level perspective: The text on the building and "
                  "the icons are nonsensical and do not form coherent words or symbols. "
                  "Therefore, this image is fake."),
    "inference_ms": 15558.7,
    "truncated": False,
    "model_repo": "AnnaGao/FakeReasoning",
    "model_revision": "official+fp16",
    "image": {"width": 1536, "height": 1024, "format": "PNG"},
}

FINETUNE = {
    "prediction": "fake",
    "reasoning": ("The image depicts a modern building with large glass windows, surrounded by "
                  "palm trees and a clear sky. Despite its seemingly authentic appearance, "
                  "certain features, such as disproportionate textures or odd lighting, hint "
                  "that this image was generated by AI. Therefore, this image is fake."),
    "inference_ms": 9903.2,
    "truncated": False,
    "model_repo": "AnnaGao/FakeReasoning",
    "model_revision": "finetuned:fakereasoning-finetuned",
    "image": {"width": 1536, "height": 1024, "format": "PNG"},
}


class H(BaseHTTPRequestHandler):
    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def _send(self, code, payload, ctype="application/json"):
        body = payload if isinstance(payload, bytes) else json.dumps(payload).encode()
        self.send_response(code)
        self._cors()
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        length = int(self.headers.get("Content-Length") or 0)
        self.rfile.read(length)
        p = self.path.rstrip("/")

        if p == "/envelope":
            self._send(200, {"finetune": FINETUNE, "official": OFFICIAL})
        elif p == "/list":
            self._send(200, [FINETUNE, OFFICIAL])
        elif p == "/flat":
            self._send(200, OFFICIAL)
        elif p == "/truncated":
            t = dict(FINETUNE, truncated=True)
            self._send(200, {"finetune": t, "official": OFFICIAL})
        elif p == "/real":
            r = dict(FINETUNE, prediction="real",
                     reasoning="The lighting is consistent and the textures behave. "
                               "Therefore, this image is real.")
            self._send(200, {"finetune": r, "official": OFFICIAL})
        elif p == "/500":
            self._send(500, {"error": "modal: function raised"})
        elif p == "/404":
            self._send(404, {"error": "not found"})
        elif p == "/notjson":
            self._send(200, b"<html>gateway</html>", "text/html")
        elif p == "/unreadable":
            self._send(200, {"something": "else"})
        elif p == "/slow":
            time.sleep(20)
            self._send(200, {"finetune": FINETUNE, "official": OFFICIAL})
        else:
            self._send(404, {"error": "unknown mock route " + p})

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    print("mock backend on http://127.0.0.1:5199")
    HTTPServer(("127.0.0.1", 5199), H).serve_forever()
